version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: tejakuncham/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: tejakuncham/backend:v1
    container_name: backend
    #command: sh -c "sleep 15 && node /app/index.js"
    depends_on: 
    - mysql
  frontend:
    image: tejakuncham/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
    - backend